messages:
  prefix: "&8[&6CREW&8]"
  no_permission: "&câœ˜ &7You are not allowed to do this!"
  error: "&câœ˜ &7Something went wrong!"
  execute_as_player: "&câœ˜ &7You may only use this as a player!"
  player_not_found: "&câœ˜ &7Could not find player!"
  player_not_online: "&câœ˜ &7This player is not online!"
  open_gui: "&bðŸ›ˆ &7Opening GUI."
  teleported: "&bðŸ›ˆ &7Your are being teleported."
  teleported_self: "&aâœ” &7Your are being teleported."
  teleported_others: "&aâœ” &7Teleporting player(s)."
  success: "&aâœ” &7Success!"
  failed: "&câœ˜ &Failed!"
  updated_gamemode: "&bðŸ›ˆ &7Your gamemode has been updated."
  updated_gamemode_other: "&aâœ” &7Updated gamemode."